services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7346
      POSTGRES_DB: game-manager
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared-network

  book-manager:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/game-manager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 7346
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      HTTP_URL_DUX_MANAGER: http://dux-manager:8080/dux-manager/api/v1
    depends_on:
      - postgres
    networks:
      - shared-network

volumes:
  postgres-data:

networks:
  shared-network:
    external: true