###################  Microservice base configuration  ###################
spring.application:
  name: game-manager
  version: 0.0.1-SNAPSHOT

# default port for HTTP:   80
# default port for HTTPS: 443
server:
  port: 8082
  servlet.context-path: /${spring.application.name}

logging.level:
  root: INFO
  org.springframework: INFO
  com.portfolio: INFO

springdoc:
  api-docs.path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# #################### DB configuration
spring.datasource:
  url: ${POSTGRES_URL}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  driver-class-name: org.postgresql.Driver

spring.jpa.hibernate.ddl-auto: create

###################  Data Provider REST configuration  ###################
http.url:
  dux-manager: "${HTTP_URL_DUX_MANAGER}"