###################  Microservice base configuration  ###################
spring.application:
  name: game-manager
  version: 0.0.1-SNAPSHOT

# default port for HTTP:   80
# default port for HTTPS: 443
server:
  port: 8082
  servlet.context-path: /${spring.application.name}

logging.level:
  root: INFO
  org.springframework: INFO
  com.portfolio: INFO

springdoc:
  api-docs.path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# #################### DB configuration
spring.datasource:
  url: jdbc:postgresql://localhost:5432/game-manager
  username: postgres
  password: 7346
  driver-class-name: org.postgresql.Driver

spring.jpa.hibernate.ddl-auto: create

###################  Data Provider REST configuration  ###################
http.url:
  dux-manager: "http://dux-manager:8080/dux-manager/api/v1"